### ISSUE TITLE
Implement Data Structures

### ISSUE THREAD

**Issue by rask24** [rask24/fdf#40]
## description
I need to define and implement the following data structures and their respective construction functions as individual modules. This will include creating the` Data`, `MlxConf`, and `ViewConf` structures and implementing the `construct_data`, `construct_mlx_conf`, and `construct_view_conf` functions.

## tasks
- [x] Define the Data structure in a dedicated module.
- [x] Define the MlxConf structure in a dedicated module.
- [x] Define the ViewConf structure in a dedicated module.
- [x] Implement the construct_data function.
- [x] Implement the construct_mlx_conf function.
- [x] Implement the construct_view_conf function.
- [x] Test construct_data

## class diagram
<img width="1087" alt="Screenshot 2024-06-21 at 23 28 12" src="https://github.com/rask24/fdf/assets/70057885/86634895-9509-46d9-8baa-efb82427cede">
