### ISSUE TITLE
Update Data Structures

### ISSUE THREAD

**Issue by rask24** [rask24/fdf#42]
## Description
Update the data structures and initialization functions to accommodate the following changes:

### Coordinate System Change
The coordinate system will be changed to place the origin (0,0) at the bottom-left corner as shown in the attached image.
Previously, the origin was at the top-left corner, but this change is necessary for proper rendering.

### Remove rot_matrix
The rot_matrix field will be removed from ViewConf.
The rotation matrix was initially intended to keep track of rotations, but it has been determined that directly manipulating points is sufficient.

### Add original_points:
A copy of points will be maintained in a new member variable original_points within the Data structure.
original_points will be const and will store the initial data, allowing operations on points while retaining the original state.
This will be useful for handling user interactions like resetting or changing the drawing method.
Drawing Method Configuration:

A new variable will be added to ViewConf to store the drawing method.
Define orthographic and isometric as enums within ViewConf. 

## Tasks
- [x] Add original_points to Data structure.
- [x] Update ViewConf Structure:
- [x] Remove rot_matrix
- [x] Add a new variable for storing the drawing method.
- [x] Define orthographic and isometric as enums.
- [x] Initialize points and original_points.
- [x] Adjust the coordinates to match the new coordinate system.
- [x] Rename set to init

## Updated class diagram
<img width="1119" alt="Screenshot 2024-06-22 at 16 10 06" src="https://github.com/rask24/fdf/assets/70057885/316f9f3f-10b3-42d2-adf0-a6b99f337407">
